services:
  gnodev:
    build: ./contract/
    ports:
      - "8888:8888"
      - "26657:26657"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/r/volos"]
      interval: 5s
      retries: 5

  tx-indexer:
    build: .
    ports:
      - "3100:3100"
    depends_on:
      gnodev:
        condition: service_healthy
    restart: on-failure

  backend:
    build: ./backend/
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - tx-indexer

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
