import { Asset } from "./columns"

// Sample data for the table
export const assets: Asset[] = [
  {
    id: "1",
    token: "Ethereum",
    symbol: "ETH",
    available: 245.35,
    apy: 3.21,
    collateralFactor: 0.85,
  },
  {
    id: "2",
    token: "Bitcoin",
    symbol: "BTC",
    available: 12.43,
    apy: 2.54,
    collateralFactor: 0.80,
  },
  {
    id: "3",
    token: "Solana",
    symbol: "SOL",
    available: 1254.67,
    apy: 5.32,
    collateralFactor: 0.70,
  },
  {
    id: "4",
    token: "USD Coin",
    symbol: "USDC",
    available: 5000.00,
    apy: 4.78,
    collateralFactor: 0.90,
  },
  {
    id: "5",
    token: "Cardano",
    symbol: "ADA",
    available: 3245.87,
    apy: 4.12,
    collateralFactor: 0.65,
  },
  {
    id: "6",
    token: "Polkadot",
    symbol: "DOT",
    available: 1876.32,
    apy: 7.85,
    collateralFactor: 0.60,
  },
  {
    id: "7",
    token: "Avalanche",
    symbol: "AVAX",
    available: 652.18,
    apy: 6.25,
    collateralFactor: 0.75,
  },
  {
    id: "8",
    token: "Chainlink",
    symbol: "LINK",
    available: 2145.90,
    apy: 4.45,
    collateralFactor: 0.62,
  },
  {
    id: "9",
    token: "Polygon",
    symbol: "MATIC",
    available: 7562.44,
    apy: 5.87,
    collateralFactor: 0.68,
  },
  {
    id: "10",
    token: "Tether",
    symbol: "USDT",
    available: 8500.00,
    apy: 4.25,
    collateralFactor: 0.88,
  },
  {
    id: "11",
    token: "Binance Coin",
    symbol: "BNB",
    available: 124.75,
    apy: 3.95,
    collateralFactor: 0.78,
  },
  {
    id: "12",
    token: "Cosmos",
    symbol: "ATOM",
    available: 952.30,
    apy: 8.12,
    collateralFactor: 0.55,
  },
  {
    id: "13",
    token: "Algorand",
    symbol: "ALGO",
    available: 4851.25,
    apy: 5.68,
    collateralFactor: 0.58,
  },
  {
    id: "14",
    token: "Uniswap",
    symbol: "UNI",
    available: 782.65,
    apy: 6.79,
    collateralFactor: 0.63,
  },
  {
    id: "15",
    token: "DAI",
    symbol: "DAI",
    available: 6500.00,
    apy: 4.65,
    collateralFactor: 0.89,
  },
] 
