import { MainSidebar } from "@/components/MainSidebar"
import { SidebarProvider } from "@/components/ui/sidebar"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-[#181c21]")}>
        <SidebarProvider>
            <MainSidebar />
            <main className="flex-1">
              {children}
            </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
